import "./globals.css";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import localFont from "next/font/local";
import Provider from "@/app/Provider";

const sans = localFont({
    display: "swap",
    variable: "--font-sans",
    src: [
        {
            path: "../../public/fonts/Georama[wdth,wght].ttf",
            weight: "100 900",
            style: "normal"
        },
        {
            path: "../../public/fonts/Georama-Italic[wdth,wght].ttf",
            weight: "100 900",
            style: "italic"
        }
    ]
});

const serif = localFont({
    display: "swap",
    variable: "--font-serif",
    src: [
        {
            path: "../../public/fonts/Labrada[wght].woff2",
            weight: "100 900",
            style: "normal"
        },
        {
            path: "../../public/fonts/Labrada-Italic[wght].woff2",
            weight: "100 900",
            style: "italic"
        }
    ]
});

export const metadata: Metadata = {
    title: {
        template: "%s | Taufik Oktama",
        default: "Taufik Oktama"
    },
    description: "Generated by create next app"
};

export default function RootLayout(props: PropsWithChildren) {
    const { children } = props;
    return (
        <html lang="en" suppressHydrationWarning className={`${sans.variable} ${serif.variable}`}>
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>
    );
}
