import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Alegreya } from "next/font/google";

const sans = localFont({
    display: "swap",
    variable: "--font-sans",
    src: [
        {
            path: "../../public/fonts/Georama[wdth,wght].ttf",
            weight: "100 900",
            style: "normal"
        },
        {
            path: "../../public/fonts/Georama-Italic[wdth,wght].ttf",
            weight: "100 900",
            style: "italic"
        }
    ]
});

const serif = Alegreya({
    subsets: ["latin"],
    weight: "variable",
    style: ["normal", "italic"],
    variable: "--font-serif"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className={`${sans.variable} ${serif.variable}`}>
            <body>{children}</body>
        </html>
    );
}
